### ISSUE TITLE
Replace `org.godotengine.Godot` with `org.godotengine.GodotSharp` in README

### ISSUE THREAD

**Issue by geekley** [flathub/org.godotengine.GodotSharp#3]
There's references to `org.godotengine.Godot` in [Installation](https://github.com/flathub/org.godotengine.GodotSharp#installation) and [Building from source](https://github.com/flathub/org.godotengine.GodotSharp#building-from-source).
Should probably be `org.godotengine.GodotSharp`.

I didn't check anywhere else (code, etc.).

**Comment by Zishan-Rahman** [comment]
> I didn't check anywhere else (code, etc.).

I just checked everywhere else and it looks like everything's correct.

**Comment by geekley** [comment]
I was worried mostly about this line https://github.com/flathub/org.godotengine.GodotSharp/blob/1ffad4129f41c8ad669261a5dc7fe8a2c5aea270/org.godotengine.GodotSharp.yaml#L132
I didn't say anything because I assumed it's meant to be this way

**Comment by Zishan-Rahman** [comment]
> I was worried mostly about this line
> 
> https://github.com/flathub/org.godotengine.GodotSharp/blob/1ffad4129f41c8ad669261a5dc7fe8a2c5aea270/org.godotengine.GodotSharp.yaml#L132
> 
> I didn't say anything because I assumed it's meant to be this way

Oh, that just changes the "name" and "icon" fields in the desktop file. In the following line, the desktop file gets moved to a new folder, and its filename gets changed to `org.godotengine.GodotSharp.desktop`:

https://github.com/flathub/org.godotengine.GodotSharp/blob/1ffad4129f41c8ad669261a5dc7fe8a2c5aea270/org.godotengine.GodotSharp.yaml#L133

`FLATPAK_ID` is, of course, `org.godotengine.GodotSharp`. So yes, it _is_ meant to be this way in the manifest. When the Flatpak is installed, the desktop file will still be called `org.godotengine.GodotSharp.desktop`.

Still, though, good call on finding the erroneous references to `org.godotengine.Godot` in the README.md file. I can't believe I didn't notice them until now! :man_facepalming:

**Comment by Zishan-Rahman** [comment]
I'm just waiting for the test build in #4 to be completed and for the completed checks to show up on GitHub, then, since nothing about the Flatpak itself changed (only the README.md file), I can merge the PR and then this issue will close by itself.
