### ISSUE TITLE
Unable to access Asset Library example projects.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [flathub/org.godotengine.GodotSharp#9]
> ![%Y%M%DT%H%m%S%t-2](https://github.com/flathub/org.godotengine.GodotSharp/assets/42837531/1026daa6-9cca-4b51-a63b-8205ed33143f)

This is the default filter configuration provided by

> ![%Y%M%DT%H%m%S%t-2](https://github.com/flathub/org.godotengine.GodotSharp/assets/42837531/71a52906-6c90-4a24-8df8-3f7a38ca1fc2)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-demo-projects/issues/920, as this issue is not specific to the Flatpak.
